### ISSUE TITLE
Asynchronous invoke on lambda function not working

### ISSUE THREAD

**Issue by shreyas44** [aws/aws-sdk-js-v3#1844]
**Describe the bug**
Calling `lambda.invokeAsync()` returns `PathNotFoundLocally: PathNotFoundException`

**SDK version number**
3.1.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the Node.js version**
v15.3.0

**To Reproduce (observed behavior)**

1. Create a basic Lambda Function
```ts
export const lambdaHandler = async (event) => {
  return {
    statusCode: 200,
    body: JSON.stringify(event),
  }
}
```

2. Create SAM config
```yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: lambda

Globals:
  Function:
    Timeout: 3

Resources:
  CreateUserSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-user-session
      Handler: dist/app.lambdaHandler
      Runtime: nodejs12.x
```

3. Run SAM
```bash
sam local start-lambda
```

4. Call lambda function from node
```ts
// app.js
const { Lambda } = require("@aws-sdk/client-lambda")

const lambda = new Lambda({
  region: "ap-south-1",
  apiVersion: "2015-03-31",
  endpoint: "http://localhost:3000",
})

lambda.invokeAsync({
  FunctionName: "CreateUserSessionFunction",
})
```

5. Run the code 
```bash
node app.js
```

**Expected behavior**
Run the lambda function named `CreateUserSessionFunction`

**Screenshots**
Logs from SAM
![Screen Shot 2020-12-27 at 4 24 33 PM](https://user-images.githubusercontent.com/46835608/103169280-449afb80-4860-11eb-8f6f-e6e661df12bc.png)
1st line is the output when called using `.invoke()`
2nd line is the output when called using `.invokeAsync()`

**Additional context**
If i replace `invokeAsync` with `invoke` which is synchronous, everything works just as expected. The `apiVersion` parameter when instantiating the Lambda object seems to be ignored altogether. If you see the request URL, it starts with `/2014-11-13` even though the API version is explicitly mentioned to be `2015-03-31`.
