### ISSUE TITLE
S3 [PutObjectCommand] memory leak

### ISSUE THREAD

**Issue by hatemalimam** [aws/aws-sdk-js-v3#1897]
**Describe the bug**
There's an apparent leak of memory when a file gets uploaded to S3, the rss memory keeps growing and never gets garbage collected.

**SDK version number**
3.2.0
**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.16.1

**To Reproduce (observed behavior)**
Clone https://github.com/hatemalimam/aws-s3-memory-leak make sure to set `BUCKET_NAME` and `REGION` in index.js,
there are some test files in files directory, when executing `yarn start` the files in that directory are uploaded sequentially, and there are memory stats before uploading the files, right after, and a delay of 10 seconds after each upload to allow any GC. 

**Expected behavior**
The RSS memory should free up.

**Screenshots**
![Screenshot 2021-01-11 at 20 58 21](https://user-images.githubusercontent.com/3439970/104219876-bfaf0500-544f-11eb-976b-9f73aa76c532.png)

**Comment by MercusChan** [comment]
We got the same issue.
This is blocked on using s3 service.

Any workarounds?

**Comment by BEPTEP** [comment]
We switched to this older library https://www.npmjs.com/package/s3-stream-upload

**Comment by hatemalimam** [comment]
@BEPTEP even the old [aws-client](https://github.com/aws/aws-sdk-js/issues/3128) has a memory issue, we have made the tests also on the suggested library, same results.

**Comment by hatemalimam** [comment]
Any update on this ? this is really killing us in production...

**Comment by elszczepano** [comment]
@hatemalimam I've downloaded your repo and updated `@aws-sdk/client-s3` to `3.35.0`. Then I've run your application in Docker:
```Dockerfile
FROM node:12.21.0-alpine3.12 AS builder
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY files/ ./files
COPY index.js index.js

FROM node:12.21.0-alpine3.12
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
CMD ["node", "index.js"]
```

and ran it with min.io in through docker-compose:
```yaml
---
version: "2.2"
services:
  aws-s3:
    image: minio/minio:RELEASE.2021-02-07T01-31-02Z
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    command: server /data --address :4570
    ports:
      - "4570:4570"
    networks:
      - custom
    logging:
      driver: "none"

  test:
    image: test
    networks:
      - custom
    depends_on:
      - aws-s3
    restart: always

networks:
  custom:
    name: custom
```

Returned results look very reasonable. I received similar results by just running it via node on my local machine (12.18.2):

![Screenshot 2021-10-06 at 14 20 03](https://user-images.githubusercontent.com/23155008/136200873-71b44c92-2192-482b-94c5-13326fcaba5e.png)

Could you confirm the issue still occurs on the latest version? Or have you skipped some important detail that I didn't take into account?
