### ISSUE TITLE
Cannot use in AWS lambda

### ISSUE THREAD

**Issue by Sheryorov** [aws/aws-sdk-js-v3#2129]
## bug
Installation taking about 150MB. Dependencies include react-native files.` sam build` twice its size and deployment fails because of oversize.

#### SDK version number
   `@aws-sdk/client-sts": "^3.8.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.18.3

## Steps to reproduce
`npm i --save @aws-sdk/client-sts`
See size of node_modules

#### Observed behavior
Installation taking about 150MB. 

#### Expected behavior
Installation should take < 150MB to deploy lambda.

**Comment by m-radzikowski** [comment]
See #2051 - I think it's the same case.

**Comment by AllanZhengYP** [comment]
Hi @Sheryorov.

Like @m-radzikowski has mentioned, the issue with the raw size of SDK client can be solved if mentioned issue is fixed. To workaround it, you can either use bundling tools(like Webpack) to bundle the code, or create a layer with V3 client. Here's an idea of the sam template you might write:

```yaml
Resources:
  someFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: someFunction/
      Handler: index.handler
      Runtime: nodejs14.x
      Layers: 
        - !Ref dynamoDBClientLayer
...
   dynamoDBClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dynamoDBClientLayer
      Description: A Lambda layer containing a single DynamoDB client from SDK v3
      LicenseInfo: Apache 2.0
      CompatibleRuntimes: 
        - nodejs14.x
        - nodejs12.x
        - nodejs10.x
      ContentUri: layers/
    Metadata:
      BuildMethod: makefile
```

It specifies sam to build a custom layer container DyanmoDB client according to `Makefile`. in the `Makefile`

```Makefile
# layers/Makefile
build-dynamoDBClientLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	npm install
	cp -rf node_modules "$(ARTIFACTS_DIR)/nodejs"
```

The `layers` folder should also include a `package.json` with all the dependency you want to put to Lambda, including `@aws-sdk/client-dynamodb`. 

[Here's the SAM doc](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html) with more guidance on building a layer
