### ISSUE TITLE
Cannot use SDK v3 with dynamodb local

### ISSUE THREAD

**Issue by Berger92** [aws/aws-sdk-js-v3#4294]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi 👋 

I've seen this issue in the past, but they have all been closed. I am migrating from my app using SDK v2 to SDK v3. I have no problems whatsoever reaching dynamodb local with v2, or the aws cli, but I can't seem to make it work with v3.

Am I doing something wrong or is there a bug here?

I've tried tinkering with config, adding fake credentials, etc. but I got nowhere.

### SDK version number

v3.231.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.12.1

### Reproduction Steps

```typescript
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({
  endpoint: 'http://localhost:8000'
});
const ddbDocClient = DynamoDBDocument.from(client);

(async () => {
  const result = await client.send(new ListTablesCommand({}));

  console.log(result);
})();
```

### Observed Behavior

```
Error: connect ECONNREFUSED ::1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8000,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

The list of local dynamodb tables

**Comment by yenfryherrerafeliz** [comment]
Hi @Berger92, thanks for opening this issue. Could you please try specifying the endpoint as follow:
```js
const client = new DynamoDBClient({
    endpoint: {
        hostname: 'localhost',
        port: 8000,
        path: '',
        protocol: 'http:',
    }
});
```

Your example code should look as follow:
```js
import {DynamoDBClient, ListTablesCommand} from '@aws-sdk/client-dynamodb';
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({
    endpoint: {
        hostname: 'localhost',
        port: 8000,
        path: '',
        protocol: 'http:',
    }
});
const ddbDocClient = DynamoDBDocument.from(client);

(async () => {
    const result = await ddbDocClient.send(new ListTablesCommand({}));

    console.log(result);
})();
```

Let me know if that works.

Thanks!

**Comment by Berger92** [comment]
Hi @yenfryherrerafeliz 👋 
Thanks for the quick response. I've tried it, but I got the same result as before 

```
Error: connect ECONNREFUSED ::1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8000,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

**Comment by Berger92** [comment]
@yenfryherrerafeliz Just one additional piece of information that might help. I am using DynamoDB Local in a Docker container, latest version.

**Comment by yenfryherrerafeliz** [comment]
Hi @Berger92, sorry for the delay in getting back. After doing some researches I found that the issue that you are getting may be due to a factor out of the SDK itself. According with the error that you are getting, seems like the connection to the specified host and port is being refused, and this could be due to different situations, maybe the specified port is not open to be accessible, out of the container, and actually did you make sure you are running the image with the right port mapping?, because it seems to be a networking issue.

Thanks!

**Comment by Berger92** [comment]
Hi @yenfryherrerafeliz . I disagree with you, because as I said in the original post, the docker container works for me perfectly with SDK v3 using Nodejs16. The problem started occurring using Nodejs 18.

**Comment by elpioramirez** [comment]
I'm having a similar issue. I'm running DynamoDB locally in a docker container. My docker-compose file is as following:

```
version: '3.9'
services:
  dynamo-wedrapp:
    container_name: 'dynamo-wedrapp'
    image: amazon/dynamodb-local
    networks:
      -  api-network
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - dynamodb-data:/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000 || exit 1" ]
      interval: 5s
      timeout: 3s
      start_period: 10s
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
volumes:
  dynamodb-data:
    name: dynamodb-data
networks:
   api-network
    driver: bridge
    name: api-network
```

then I have SAM installed and my template file is as follows:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  development-api

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs18.x

Resources:
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_items/
      Handler: app.handler
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /get-items/
            Method: get
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "false"
```
In this previous file, I tried removing the USE_LOCAL_DYNAMODB environment variable

My lambda function is the following:
```
import { DynamoDBClient, QueryCommand } from '@aws-sdk/client-dynamodb';
const dynamodbClient = new DynamoDBClient({
    region: "localhost",
    endpoint: "http://localhost:8000"
});

const tableName = 'items_table';

export const handler = async (event, context) => {

   // Hard coding the category to validate the connection
    const queryCommand = new QueryCommand({
        TableName: tableName,
        KeyConditionExpression: 'itemCategory= :itemCategory )',
        ExpressionAttributeValues: {
            ':itemCategory':  "12382ABC"
        },
    });

    try {
        const result = await dynamodbClient.send(queryCommand);
        const items = result.Items;
        return {
            statusCode: 200,
            body: JSON.stringify(items)
        };
    } catch (err) {
        return {
            statusCode: 500,
            body: JSON.stringify(err)
        };
    }
};
```

In this file, I tried toggling the endpoint "http://localhost:8000" to "http://host.docker.internal:8000" but I got an error of Resource not found:

```
{
    "name": "ResourceNotFoundException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "f9925f6b-646d-4e55-9d0d-ab601a792a1a",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "__type": "com.amazonaws.dynamodb.v20120810#ResourceNotFoundException"
}
```

To start SAM I run the following command:
`sam local start-api --docker-network api-network --port 3001 --debug`

Also I tried `sam local start-api --port 3001 --debug`

The other error I receive is the following:

```
{
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 8000,
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    }
}
```
